// Declaration merging with the `Cloudflare.Env` interface generated by
// `npx wrangler types` (worker-configuration.d.ts, gitignored/regenerated --
// see .gitignore). That file only knows about bindings declared in
// wrangler.jsonc (R2, KV, D1, etc.); Worker *secrets* are never written to
// wrangler.jsonc, so they aren't picked up automatically and need to be
// declared here by hand to keep `env.TURNSTILE_SECRET_KEY` etc. type-safe
// in route handlers. Set the real values with
// `npx wrangler secret put <NAME>` once the Cloudflare account is
// authenticated -- see docs/migration/production-cutover-checklist.md §14.
declare namespace Cloudflare {
  interface Env {
    /** Cloudflare Turnstile secret key, used to verify tokens server-side. */
    TURNSTILE_SECRET_KEY?: string;
    /** Signs/verifies time-limited R2 file-retrieval URLs (src/app/api/estimate/files/[key]/route.ts). */
    FILE_RETRIEVAL_SIGNING_SECRET?: string;
    /** Signs/verifies the batch token that authorizes deleting an upload batch's own R2 objects on cleanup. */
    UPLOAD_BATCH_SIGNING_SECRET?: string;
  }
}
